name: CI-CD Pipeline 
on: 
  push: 
   branches: 
   - main 
jobs: 
 deploy:
       runs-on: ubuntu-latest
       steps:
         - name: Deploy to EC2
           uses: appleboy/ssh-action@v0.1.6
           with:
             host: ${{ secrets.HOST }}
             username: ${{ secrets.USER_IP }}
             key: ${{ secrets.SSH_KEY }}
             script: |
                docker pull ${{ secrets.DOCKERHUB_USER }}/mean-backend
                docker pull ${{ secrets.DOCKERHUB_USER }}/mean-frontend

                docker stop backend || true
                docker stop frontend || true

                docker rm backend || true
                docker rm frontend || true

                docker run -d --name backend -p 5000:5000 ${{ secrets.DOCKERHUB_USER }}/mean-backend
                docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USER }}/mean-frontend
                
