name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.Docker_user }}
        password: ${{ secrets.Docker_password }}

    - name: Build Backend
      run: |
        docker build -t ${{ secrets.Docker_user }}/mean-backend ./backend
        docker push ${{ secrets.Docker_user }}/mean-backend

    - name: Build Frontend
      run: |
        docker build -t ${{ secrets.Docker_user }}/mean-frontend ./frontend
        docker push ${{ secrets.Docker_user }}/mean-frontend
