name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Backend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/mean-backend ./backend
        docker push ${{ secrets.DOCKERHUB_USER }}/mean-backend

    - name: Build Frontend
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/mean-frontend ./frontend
        docker push ${{ secrets.DOCKERHUB_USER }}/mean-frontend

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USER_IP }}
       key: ${{ secrets.SSH_KEY }}
       script: |
        cd mean-crud-docker-deployment
        ./deploy.sh 
